### ISSUE TITLE
Add example for securely connecting to Kafka (and a potential bug?)

### ISSUE THREAD

**Issue by andrijadukic-syntio** [apache/camel-kamelets-examples#19]
Hi, an example such as the [Kafka to IBM MQ](https://github.com/apache/camel-kamelets-examples/tree/main/jbang/kafka-mq) one, but for showing usage of security mechanisms would be much appreciated, as any production use case certainly requires something like SASL_PLAIN to be used.

We've attempted the exact integration I linked to, but through the "base" kafka source kamelet. The route we tried is (skipping irrelevant parts):

```yaml
...
- route:
    id: "kafka-to-mq"
    from:
      uri: "kamelet:kafka-source"
      parameters:
        bootstrapServers: "{{kafka.bootstrapServers}}"
        topic: "{{kafka.kafka-to-mq-topic}}"
        saslMechanism: PLAIN
        securityProtocol: SASL_SSL
        user: "$ConnectionString"
        password: "<PASSWORD>"
        deserializeHeaders: true
...
```

However, this doesn't work because, for some reason, authentication is failing. The stacktrace says nothing useful, as it seems like a standard error you'd get from wrong credentials being used.
One potential issue that's happening is incorrect parsing due to the '$' character at the start of the username, but basically the authentication process fails for some reason.

To make sure this is an issue with the kamelet, and not with our configuration, we've also tried out the Camel Core Kafka source from which this kamelet is based on, which then looks something like this:

```yaml
...
- route:
    id: "kafka-to-mq"
    from:
      uri: "kafka:{{kafka.kafka-to-mq-topic}}"
      parameters:
        brokers: "{{kafka.bootstrapServers}}"
        groupId: "{{kafka.groupId}}"
        saslJaasConfig: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password={{kafka.password}};'
        saslMechanism: PLAIN
        securityProtocol: SASL_SSL
...
```

This works as expected, but then the issue is that any custom header we have in Kafka won't be passed over to IBM MQ (but this is a separate issue that I won't get into in this context).

One thing we noticed, which might be the reason behind what's wrong is the fact that, in the case of the kamelet kafka source, the "compiled" (from the resolved uri) saslJaasConfig has single quotes around the username and password parts, but in the kafka source (the one which is working properly, aside from an issue with the headers), double quotes are used instead.
We've also tried to add an additional '$' in the username, in order to escape it (so "$$ConnectionString"), and trying wrapping the username in double quotes, but nothing works.

Used versions:
- camel-k: dependency=mvn:com.ibm.mq:com.ibm.mq.allclient:9.2.5.0
- camel-k: dependency=mvn:org.apache.camel.kamelets:camel-kamelets-utils:3.20.1.1

Additional notes:
The "Kafka" cluster we're attempting to connect to is actually an Azure Event Hubs namespace, but with Kafka enabled. This isn't relevant since the Camel Core Kafka source works with Event Hubs (since Event Hubs fully supports the Kafka Consumer/Producer API), but I'm mentioning it just in case (and to also explain the strange username).

**Comment by oscerd** [comment]
You should use this: https://github.com/apache/camel-kamelets/blob/main/kamelets/kafka-source.kamelet.yaml

I'll update the example accordingly

**Comment by andrijadukic-syntio** [comment]
> You should use this: https://github.com/apache/camel-kamelets/blob/main/kamelets/kafka-source.kamelet.yaml
> 
> I'll update the example accordingly

Hi @oscerd , thanks for replying so quickly!
The first snippet (the route definition that we've tried using but fails to authenticate) is the one you linked (so not the kafka-not-secured-source, but the kafka-source kamelet), but unfortunately, it's not working:
```yaml
...
- route:
    id: "kafka-to-mq"
    from:
      uri: "kamelet:kafka-source"
      parameters:
        bootstrapServers: "{{kafka.bootstrapServers}}"
        topic: "{{kafka.kafka-to-mq-topic}}"
        saslMechanism: PLAIN
        securityProtocol: SASL_SSL
        user: "$ConnectionString"
        password: "<PASSWORD>"
        deserializeHeaders: true
...
```

Like I said in the issue description: when inspecting the source of the kamelet, I'd say the only difference between the way the kamelet sets up the saslJaasConfig compared to the Camel core route that we've tried are the quotes (single quotes compared to double). It might be that Azure Event Hubs expects double quotes here; I'm not really sure why it matters what quote type is being used.
